import SolutionPage from "@/components/SolutionPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cold & Cool Storage Solutions - SPI Coatings",
  description: "Reduce energy costs in refrigerated storage with thermal insulation coatings that block solar heat gain.",
};

export default function ColdCoolStoragePage() {
  return (
    <SolutionPage
      title="Cold & Cool Storage"
      subtitle="Reduce refrigeration energy costs by blocking solar heat gain at the source"
      description="Cold storage and refrigerated warehouses are among the highest energy-consuming commercial buildings. The refrigeration system must overcome not only the heat generated by goods and occupancy, but also heat entering through the building envelope — especially solar heat gain through the roof. By applying Super Therm® to cold store roofs, the solar heat gain can be dramatically reduced, cutting the refrigeration load and delivering significant energy savings. Multiple documented case studies show energy savings of 20-40% in cold storage applications."
      benefits={[
        "Reduce refrigeration energy costs by 20-40%",
        "Reduce solar heat gain through cold store roofs",
        "Maintain cold chain integrity more efficiently",
        "Lower capital cost for refrigeration equipment in new builds",
        "Reduce CO₂ emissions from refrigeration systems",
        "Quick payback — typically 12-24 months",
        "Can be applied to existing cold stores without disruption",
        "Compatible with most existing roof finishes",
      ]}
      products={[
        {
          name: "Super Therm®",
          description: "Dramatically reduces solar heat gain through cold store roofs. Documented energy savings of 20-40% in refrigerated warehouses.",
          href: "/coating-products/super-therm",
        },
        {
          name: "Sunshield",
          description: "High solar reflectance coating for cold store roofs — cost-effective solution for reducing refrigeration loads.",
          href: "/coating-products/sunshield",
        },
        {
          name: "SP Liquid Membrane®",
          description: "Waterproof membrane for cold store roofs and walls — prevents moisture ingress that can damage insulation.",
          href: "/coating-products/sp-liquid-membrane",
        },
      ]}
      accentColor="#006064"
    />
  );
}
